#!/bin/bash
# Generate daily performance summary
# Run every day at 8:00 AM GMT+7

VPS="root@188.166.227.8"
REPORT_FILE="$HOME/clawd/vps-monitor-logs/daily-report-$(date +%Y%m%d).md"
LOG_DIR="$HOME/clawd/vps-monitor-logs"
mkdir -p "$LOG_DIR"

DATE=$(date '+%Y-%m-%d')

echo "# 📊 DEX Trading VPS - Daily Report" > "$REPORT_FILE"
echo "**Date**: $DATE" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Bot Status
echo "## 🤖 Bot Status" >> "$REPORT_FILE"
BOT_INFO=$(ssh "$VPS" "
  RUNNING=0
  TOTAL=0
  for bot in \
    'lighter-rust-rabby:lighter-rust-rabby.service' \
    'lighter-rust-nanox:lighter-rust-nanox.service' \
    'reya-grid:reya-grid-v2.1.service' \
    'aster-bnb-sol:aster-bnb-sol-grid.service' \
    'paradex-grid:paradex-grid.service' \
    'hyperliquid-sol:hyperliquid-sol.service' \
    'aster-rebalance:aster-rebalance.service' \
    'apex-grid:apex-grid-points.service' \
    'pacifica:pacifica-aster-bot.service'
  do
    name=\$(echo \$bot | cut -d: -f1)
    service=\$(echo \$bot | cut -d: -f2)
    status=\$(systemctl is-active \$service 2>/dev/null)

    if [ \"\$status\" = 'active' ]; then
      pid=\$(systemctl show -p MainPID \$service 2>/dev/null | cut -d= -f2)
      mem=\$(ps -p \$pid -o %mem= 2>/dev/null | tr -d ' ')
      echo \"✅ \$(printf '%-25s' \$name) [PID: \$pid | MEM: \${mem}%%]\"
      ((RUNNING++))
    else
      echo \"❌ \$(printf '%-25s' \$name) [NOT RUNNING]\"
    fi
    ((TOTAL++))
  done
  echo \"Running: \$RUNNING/\$TOTAL\"
")

echo "$BOT_INFO" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# System Resources
echo "## 💻 System Resources" >> "$REPORT_FILE"

MEMORY=$(ssh "$VPS" "free -h | grep Mem | awk '{print \"Memory: \"\$3\"/\"\$2\" (\"int(\$3/\$2*100)\"%)\", \"Available: \"\$7}'")
DISK=$(ssh "$VPS" "df -h / | tail -1 | awk '{print \"Disk: \"\$3\"/\"\$2\" (\"\$5\")\"}'")
UPTIME=$(ssh "$VPS" "uptime | awk '{print \"Uptime: \"\$3\" days, \"substr(\$5,1,5)}'")
LOAD=$(ssh "$VPS" "uptime | awk -F'load average:' '{print \"Load: \"\$2}'")

echo "- $MEMORY" >> "$REPORT_FILE"
echo "- $DISK" >> "$REPORT_FILE"
echo "- $UPTIME" >> "$REPORT_FILE"
echo "- $LOAD" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Recent Errors
echo "## ⚠️ Errors/Issues (Last 24h)" >> "$REPORT_FILE"
ERRORS=$(ssh "$VPS" "
  find /root/bots -name '*.log' -mtime -1 -exec grep -iE 'error|exception|failed|traceback' {} \; 2>/dev/null | \
  head -10 || echo 'No errors found'
")

if [ "$ERRORS" != "No errors found" ]; then
  echo "\`\`\`" >> "$REPORT_FILE"
  echo "$ERRORS" >> "$REPORT_FILE"
  echo "\`\`\`" >> "$REPORT_FILE"
else
  echo "✅ No critical errors found" >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# Performance Summary (basic)
echo "## 💰 Performance Summary" >> "$REPORT_FILE"
echo "> Note: Profit/Loss tracking requires implementation" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "- Total Volume: TBD" >> "$REPORT_FILE"
echo "- Total PnL: TBD" >> "$REPORT_FILE"
echo "- Best Performing Bot: TBD" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Footer
echo "---" >> "$REPORT_FILE"
echo "*Report generated by Clawd VPS Monitor*" >> "$REPORT_FILE"

# Display report
cat "$REPORT_FILE"

echo ""
echo "Report saved to: $REPORT_FILE"
echo "Sending to Discord channel #dex-trading-vps..."

# Send to Discord (format for Discord - remove markdown code blocks)
DISCORD_MESSAGE="📊 **DEX Trading VPS - Daily Report**

**Date**: $DATE

**🤖 Bot Status:**
$(echo "$BOT_INFO" | sed 's/✅/✅ /;s/❌/❌ /' | grep -v 'Running:')

**Running: $(echo "$BOT_INFO" | grep 'Running:' | cut -d' ' -f2)**

**💻 System Resources:**
• $MEMORY
• $DISK
• $UPTIME
• $LOAD

**⚠️ Errors/Issues (Last 24h):**
$([ "$ERRORS" != "No errors found" ] && echo "See logs for details" || echo "✅ No critical errors found")

**💰 Performance Summary:**
> Note: Profit/Loss tracking requires implementation
• Total Volume: TBD
• Total PnL: TBD

---
*Report generated by Clawd VPS Monitor*"

# Save for manual send (or use Clawdbot session to send)
echo "$DISCORD_MESSAGE" > "$LOG_DIR/discord-message-$(date +%Y%m%d).txt"
echo "Discord message saved to: $LOG_DIR/discord-message-$(date +%Y%m%d).txt"
echo ""
echo "To send via Clawdbot, run:"
echo "  sessions_spawn 'Send this to discord channel 1466281866163392533: $(cat $LOG_DIR/discord-message-$(date +%Y%m%d).txt | head -5)...'"
